### ISSUE TITLE
issuse in loading pre-trained model with torch

### ISSUE THREAD

**Issue by danieljf24** [imodpasteur/lutorpy#39]
Hello, everayone. I'd like to load a pre-trained torch model using lutorpy, but I failed. Your help will be appreciated.
The codes are as follows:

**Save the torch model**

```
require 'nn';
mlp = nn.Sequential()
mlp:add(nn.Linear(10, 10))
mlp:add(nn.Tanh())
mlp:add(nn.Linear(10, 10))
mlp:add(nn.Tanh())
mlp:add(nn.Linear(10, 2))
mlp:add(nn.LogSoftMax())
print(mlp)

input = torch.Tensor(1,10):copy(torch.range(1, 10))
print(input)
out = mlp:forward(input)
print(out)

torch.save('test.t7', mlp)
```

**Load the troch model and apply it with lutorpy**

```
import numpy as np
import lutorpy as lua

# load your torch file(for example xx.t7 containing the model and weights)
model = torch.load('test.t7')

arr = np.array(range(10))
x = torch.fromNumpyArray(arr)

yt = model._forward(x)
yn = yt.asNumpyArray()
print yn
```

**Errors**

```
Traceback (most recent call last):
  File "test.lutorpy.py", line 5, in <module>
    model = torch.load('test.t7')
  File "lutorpy/_lupa.pyx", line 562, in lutorpy._lupa._LuaObject.__call__ (lutorpy/_lupa.c:9459)
  File "lutorpy/_lupa.pyx", line 1658, in lutorpy._lupa.call_lua (lutorpy/_lupa.c:25877)
  File "lutorpy/_lupa.pyx", line 1667, in lutorpy._lupa.execute_lua_call (lutorpy/_lupa.c:25987)
  File "lutorpy/_lupa.pyx", line 1620, in lutorpy._lupa.raise_lua_error (lutorpy/_lupa.c:25297)
lutorpy._lupa.LuaError: ...niel/software/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.Sequential>
```

**Comment by oeway** [comment]
Try to add require('nn'), because you error indicate that nn module is not
imported.

On Thu, 9 Feb 2017 at 07:23 danieljf24 <notifications@github.com> wrote:

Hello, everayone. I'd like to load a pre-trained torch model using lutorpy,
but I failed. Your help will be appreciated.
The codes are as follows:

Save the torch model
`require 'nn';

mlp = nn.Sequential()

mlp:add(nn.Linear(10, 10))
mlp:add(nn.Tanh())
mlp:add(nn.Linear(10, 10))
mlp:add(nn.Tanh())

mlp:add(nn.Linear(10, 2))
mlp:add(nn.LogSoftMax())

print(mlp)

input = torch.Tensor(1,10):copy(torch.range(1, 10))
print(input)

out = mlp:forward(input)
print(out)

torch.save('test.t7', mlp)
`

Load the troch model and apply it with lutorpy
`import numpy as np
import lutorpy as lua
load your torch file(for example xx.t7 containing the model and weights)

model = torch.load('test.t7')
generate your input data with numpy

arr = np.array(range(10))
convert your numpy array into torch tensor

x = torch.fromNumpyArray(arr)
apply model forward method with "._" syntax(which is equivalent to ":" in
lua)

yt = model._forward(x)
convert to numpy array

yn = yt.asNumpyArray()

print yn`

Errors
Traceback (most recent call last): File "test.lutorpy.py", line 5, in
<module> model = torch.load('test.t7') File "lutorpy/_lupa.pyx", line 562,
in lutorpy._lupa._LuaObject.__call__ (lutorpy/_lupa.c:9459) File
"lutorpy/_lupa.pyx", line 1658, in lutorpy._lupa.call_lua
(lutorpy/_lupa.c:25877) File "lutorpy/_lupa.pyx", line 1667, in
lutorpy._lupa.execute_lua_call (lutorpy/_lupa.c:25987) File
"lutorpy/_lupa.pyx", line 1620, in lutorpy._lupa.raise_lua_error
(lutorpy/_lupa.c:25297) lutorpy._lupa.LuaError:
...niel/software/torch/install/share/lua/5.1/torch/File.lua:343: unknown
Torch class <nn.Sequential>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/imodpasteur/lutorpy/issues/39>, or mute the thread

**Comment by danieljf24** [comment]
Thanks very much @oeway . I have already fixed it.

**Comment by shauryauppal** [comment]
@danieljf24 How did you fix it?

I am facing the same issue.
